---
- hosts: 127.0.0.1
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
  - name: create docker container
    docker_container:
      name: mycontainer
      image: ubuntu
      state: started
