---
- hosts: 127.0.0.1
  remote_user: deployer
  become: yes
  become_method: sudo
  tasks:
  - name: destroy docker container
    docker_container:
      name: mycontainer
      image: ubuntu
      state: absent
